kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Retain"
parameters:
  numberOfReplicas: "1"
  migratable: "true"
  dataLocality: "strict-local"