global:
  nodeSelector:
    storage: longhorn

networkPolicies:
  enabled: true
  type: ""

persistence:
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  reclaimPolicy: Retain
  migratable: "true"

defaultSettings:
  replicaAutoBalance: least-effort
  defaultLonghornStaticStorageClass: longhorn
  recurringJobMaxRetention: 30
  systemManagedComponentsNodeSelector: storage:longhorn
  nodeDrainPolicy: allow-if-replica-is-stopped
  concurrentReplicaRebuildPerNodeLimit: "3"
  concurrentAutomaticEngineUpgradePerNodeLimit: "3"
  removeSnapshotsDuringFilesystemTrim: "true"

longhornUI:
  replicas: 2

metrics:
  serviceMonitor:
    enabled: true