apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  sources:
    - repoURL: https://releases.rancher.com/server-charts/stable
      chart: rancher
      targetRevision: 2.10.3
      helm:
        valueFiles:
          - $values/rancher/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: rancher