apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  source:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      chart: csi-driver-smb
      targetRevision: 1.17.0