apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-private
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: git@github.com:villepaukkunen/homelab-private.git
    targetRevision: HEAD
    path: applications
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd