apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://charts.goauthentik.io/
      chart: authentik
      targetRevision: 2025.8.4
      helm:
        valueFiles:
          - $values/authentik/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: authentik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik