apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://immich-app.github.io/immich-charts
      chart: immich
      targetRevision: 0.9.3
      helm:
        valueFiles:
          - $values/immich/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: immich
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich