apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: registry-1.docker.io/cloudpirates
      chart: valkey
      targetRevision: 0.23.0
      helm:
        valueFiles:
          - $values/immich/valkey/values.yml
    - repoURL: https://secustor.dev/helm-charts
      chart: immich
      targetRevision: 2.0.1
      helm:
        valueFiles:
          - $values/immich/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: immich
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich