apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-gpu
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://intel.github.io/helm-charts
      chart: intel-device-plugins-gpu
      targetRevision: 0.35.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system