apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.9.0
      helm:
        valueFiles:
          - $values/longhorn/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: longhorn
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system