apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/villepaukkunen/homelab.git
    targetRevision: HEAD
    path: mealie
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mealie