apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: registry.k8s.io/nfd/charts
      chart: node-feature-discovery
      targetRevision: 0.18.2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: node-feature-discovery