apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://portainer.github.io/k8s/
      chart: portainer
      targetRevision: 1.0.69
      helm:
        valueFiles:
          - $values/portainer/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: portainer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer