apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://releases.rancher.com/server-charts/stable
      chart: rancher
      targetRevision: 2.12.1
      helm:
        valueFiles:
          - $values/rancher/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: rancher
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cattle-system