apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      path: searxng
  destination:
    server: "https://kubernetes.default.svc"
    namespace: searxng