apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracearr
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: registry-1.docker.io/cloudpirates
      chart: redis
      targetRevision: 0.26.4
      helm:
        valueFiles:
          - $values/tracearr/redis-values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: tracearr
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tracearr