apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/villepaukkunen/homelab.git
    targetRevision: HEAD
    path: vaultwarden
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vaultwarden