apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
    - repoURL: https://bryopsida.github.io/wireguard-chart
      chart: wireguard
      targetRevision: 0.30.0
      helm:
        valueFiles:
          - $values/wireguard/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: wireguard
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wireguard