apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  sources:
    - repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      chart: plex-media-server
      targetRevision: 0.8.0
      helm:
        valueFiles:
          - $values/plex/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      path: plex
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: plex
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.mandariini.uk`)
      kind: Rule
      services:
        - name: plex
          port: 32400
  tls:
    secretName: mandariini-uk-tls