pms:
  configExistingClaim: "plex-config"

nodeSelector:
  plex: "true"

extraVolumeMounts:
  - name: media
    mountPath: /data

extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: media