pms:
  configExistingClaim: "config"

nodeSelector:
  plex: "true"

extraVolumeMounts:
  - name: data
    mountPath: /data

extraVolumes:
  - name: data
    persistentVolumeClaim:
      claimName: data