apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets
  namespace: netbootxyz
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: netbootxyz-assets
  storageClassName: nfs-csi