apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9
  namespace: bind9
data:
  named.conf: |
    acl internal {
      10.0.0.0/8;
      172.16.0.0/12;
      192.168.0.0/16;
    };

    options {
      directory "/var/cache/bind";
      allow-query { internal; };
      forwarders {
        10.43.0.11;
        10.43.0.12;
        10.43.0.13;
        10.43.0.14;
        10.43.0.15;
        10.43.0.16;
      };
    };

    zone "mandariini.uk" {
      type primary;
      file "mandariini.uk";
    };

    zone "paukkunen.de" {
      type primary;
      file "paukkunen.de";
    };