apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi