apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tracearr-pg
  namespace: tracearr
spec:
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  instances: 2
  affinity:
    podAntiAffinityType: required
    nodeSelector:
      storage: longhorn
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescaledb-ha
    major: 18
  postgresUID: 1000
  postgresGID: 1000
  bootstrap:
    initdb:
      database: tracearr
      owner: tracearr
      secret:
        name: tracearr-postgres-credentials
  storage:
    storageClass: longhorn-single-replica
    size: 2Gi