fullnameOverride: tracearr-redis

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 50%

auth:
  existingSecret: "tracearr-redis-credentials"
  existingSecretPasswordKey: "password"

persistence:
  existingClaim: redis

nodeSelector:
  storage: longhorn