fullnameOverride: tracearr-redis

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate

auth:
  existingSecret: "tracearr-redis-credentials"
  existingSecretPasswordKey: "password"

persistence:
  existingClaim: redis

nodeSelector:
  storage: longhorn