apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 35.0.0
      helm:
        valueFiles:
          - $values/traefik/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik2.mandariini.uk`)
      middlewares:
##        - name: traefik-dashboard-basicauth
##          namespace: traefik
        - name: authentik
          namespace: authentik
      priority: 10
      services:
        - name: api@internal
          kind: TraefikService
    - kind: Rule
      match: "Host(`traefik2.mandariini.uk`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
          - kind: Service
            name: ak-outpost-authentik-embedded-outpost
            port: 9000
  tls:
    secretName: mandariini-uk-tls