apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  headers:
    forceSTSHeader: true
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true