image:
  registry: docker.io
  repository: library/nextcloud
  flavor: apache
  tag: 33.0.2
  pullPolicy: IfNotPresent

nextcloud:
  host: cloud.mandariini.uk
  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  trustedDomains: cloud.mandariini.uk
  mail:
    enabled: true
    fromAddress: cloud
    domain: mandariini.uk
    smtp:
      secure: ""
      port: 587
      authtype: LOGIN
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.42.0.0/16',
          2 => '10.43.0.0/16',
          3 => '103.21.244.0/22',
          4 => '103.22.200.0/22',
          5 => '103.31.4.0/22',
          6 => '104.16.0.0/13',
          7 => '104.24.0.0/14',
          8 => '108.162.192.0/18',
          9 => '131.0.72.0/22',
          10 => '141.101.64.0/18',
          11 => '162.158.0.0/15',
          12 => '172.64.0.0/13',
          13 => '173.245.48.0/20',
          14 => '188.114.96.0/20',
          15 => '190.93.240.0/20',
          16 => '197.234.240.0/22',
          17 => '198.41.128.0/17',
          18 => '2400:cb00::/32',
          19 => '2606:4700::/32',
          20 => '2803:f800::/32',
          21 => '2405:b500::/32',
          22 => '2405:8100::/32',
          23 => '2a06:98c0::/29',
          24 => '2c0f:f248::/32',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
  securityContext:
    allowPrivilegeEscalation: false
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    fsGroupChangePolicy: "OnRootMismatch"
  mariaDbInitContainer:
    securityContext:
      allowPrivilegeEscalation: false

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: mariadb-username
    passwordKey: mariadb-password

mariadb:
  enabled: true
  auth:
    existingSecret: envsecrets
  primary:
    nodeSelector:
      storage: longhorn
    persistence:
      enabled: true
      existingClaim: db

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    nodeSelector:
      storage: longhorn
    persistence:
      enabled: true
      existingClaim: redis
  replica:
    persistence:
      enabled: false

cronjob:
  enabled: true
  type: cronjob
  cronjob:
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - nextcloud
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - app
            topologyKey: kubernetes.io/hostname
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsUser: 33
      runAsGroup: 33
      capabilities:
        drop:
        - ALL

persistence:
  enabled: true
  existingClaim: config
  nextcloudData:
    enabled: true
    existingClaim: data

nodeSelector:
  storage: longhorn