image:
  repository: nextcloud
  flavor: apache
  tag: 31.0.7

nextcloud:
  host: cloud.mandariini.uk
  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
    smtpUsernameKey: smtp-username
    smtpPasswordKey: smtp-password
    smtpHostKey: smtp-host
  trustedDomains: cloud.mandariini.uk
  mail:
    enabled: true
    fromAddress: cloud
    domain: mandariini.uk
    smtp:
      secure: ""
      port: 587
      authtype: LOGIN
  extraEnv:
    - name: APACHE_DISABLE_REWRITE_IP
      value: "1"
    - name: TRUSTED_PROXIES
      value: 192.168.10.220 10.42.0.0/16
    - name: NEXTCLOUD_INIT_HTACCESS
      value: "true"

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true

  existingSecret:
    enabled: true
    secretName: envsecrets
    usernameKey: mariadb-username
    passwordKey: mariadb-password

mariadb:
  enabled: true
  image:
    tag: 10.6
  auth:
    existingSecret: envsecrets
  primary:
    persistence:
      enabled: true
      existingClaim: database

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      existingClaim: redis-master
  replica:
    persistence:
      enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
  existingClaim: data

  nextcloudData:
    enabled: true
    existingClaim: userdata