apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  instances: 2
  affinity:
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials
  storage:
    storageClass: longhorn-single-replica
    size: 2Gi