apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-authentik-rw
  namespace: authentik
spec:
  cluster:
    name: authentik-pg
  instances: 2
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"