---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  volumeName: postgresql
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  volumeName: redis
  resources:
    requests:
      storage: 1Gi