common:
  config:
    vectorExtension: ""
  postgres:
    host: immich-pg-rw
    existingSecret:
      enabled: true
      secretName: immich-postgres-credentials
      usernameKey: username
      passwordKey: password
  redis:
    host: immich-valkey-headless
    existingSecret:
      enabled: true
      secretName: immich-valkey-credentials
      passwordKey: password
server:
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
  volumeMounts:
    - name: uploads
      mountPath: /data
  volumes:
    - name: uploads
      persistentVolumeClaim:
        claimName: data
machineLearning:
  enabled: true
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
  volumeMounts:
    - mountPath: /.config
      name: emptydir
      subPath: conf-dir
    - mountPath: /.cache
      name: emptydir
      subPath: cache-dir
  volumes:
    - emptyDir: {}
      name: emptydir