apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: tracearr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
