global:
  domain: argocd.mandariini.uk
configs:
  cm:
    dex.config: |
      connectors:
        - config:
            issuer: https://authentik.mandariini.uk/application/o/argocd/
            clientID: $authentik:clientID
            clientSecret: $authentik:clientSecret
            insecureEnableGroups: true
            scopes:
              - openid
              - profile
              - email
          name: authentik
          type: oidc
          id: authentik
  params:
    server.insecure: true
  rbac:
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly