---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun
  namespace: unbound
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  volumeName: gluetun
  storageClassName: nfs-csi