---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound-no
  name: unbound-no
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound-no
  template:
    metadata:
      labels:
        app: unbound-no
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: release
                    operator: In
                    values:
                      - pihole2
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: unbound-no-gluetun
          image: qmcgaw/gluetun:v3.40.0
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: dns
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: gluetun-wg0-conf-no-volume
              mountPath: /gluetun/wireguard/wg0.conf
              subPath: wg0.conf
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: SERVER_REGIONS
              value: Norway
            - name: DNS_KEEP_NAMESERVER
              value: 'on'
          envFrom:
            - secretRef:
                name: envsecrets
      containers:
        - name: unbound-no
          image: mvance/unbound:1.22.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: unbound-main-conf-volume
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: unbound-a-conf-volume
              mountPath: /opt/unbound/etc/unbound/a-records.conf
              subPath: a-records.conf
      volumes:
        - name: gluetun-wg0-conf-no-volume
          secret:
            secretName: gluetun-wg0-conf-pia-no
        - name: unbound-main-conf-volume
          configMap:
            name: unbound-main-conf
        - name: unbound-a-conf-volume
          configMap:
            name: unbound-a-records-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unbound-no
  name: unbound-no
  namespace: pihole
spec:
  selector:
    app: unbound-no
  type: ClusterIP
  ports:
    - name: dns
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53