apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  sources:
    - repoURL: https://portainer.github.io/k8s/
      chart: portainer
      targetRevision: 1.0.64
      helm:
        valueFiles:
          - $values/portainer/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values
      path: portainer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.mandariini.uk`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: mandariini-uk-tls