apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: 1.0.60
    helm:
      releaseName: portainer
      valueFiles:
        - values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.mandariini.uk`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    secretName: mandariini-uk-tls