---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: portainer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn