---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-srv
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "eth0",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "192.168.10.0/24", "gw": "192.168.10.33" },
          { "dst": "192.168.20.0/24", "gw": "192.168.10.33" },
          { "dst": "10.34.0.0/24", "gw": "192.168.10.33" }
        ]
      }
    }