global:
  checkNewVersion: false
  sendAnonymousUsage: false

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  kind: DaemonSet
  revisionHistoryLimit: 3

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.5.1"

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: true

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          priority: 10
  websecure:
    http:
      encodedCharacters:
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false
      tls:
        enabled: true
    http3:
      enabled: false
  webext:
    port: 8001
    expose:
      default: true
    exposedPort: 81
    http:
      redirections:
        entryPoint:
          to: websecxt
          scheme: https
          permanent: true
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "10.43.0.0/16"
  websecxt:
    port: 8444
    expose:
      default: true
    exposedPort: 444
    http:
      encodedCharacters:
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false
      middlewares:
        - traefik-bouncer@kubernetescrd
      tls:
        enabled: true
    http3:
      enabled: false
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "10.43.0.0/16"

service:
  enabled: true
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.10.55

rbac:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"