---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: frooodle/s-pdf:1.1.1
          env:
            - name: DOCKER_ENABLE_SECURITY
              value: "true"
            - name: SECURITY_ENABLELOGIN
              value: "true"
            - name: SECURITY_OAUTH2_ENABLED
              value: "true"
            - name: SECURITY_OAUTH2_AUTOCREATEUSER
              value: "true"
            - name: SECURITY_OAUTH2_ISSUER
              value: "https://auth.mandariini.uk/application/o/pdf/"
            - name: SECURITY_OAUTH2_PROVIDER
              value: "Authentik"
            - name: SECURITY_LOGINMETHOD
              value: "oauth2"
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: "false"
            - name: LANGS
              value:
                en_GB
                de_DE
                fi_FI
            - name: SYSTEM_ENABLEANALYTICS
              value: "false"
          envFrom:
            - secretRef:
                name: envsecrets
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          volumeMounts:
            - name: trainingdata
              mountPath: /usr/share/tessdata
            - name: config
              mountPath: /configs
      volumes:
        - name: trainingdata
          persistentVolumeClaim:
            claimName: stirling-pdf
        - name: config
          persistentVolumeClaim:
            claimName: config