---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi