---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
        - name: stirling-pdf
          image: frooodle/s-pdf:0.45.3
          env:
            - name: DOCKER_ENABLE_SECURITY
              value: "true"
            - name: SECURITY_ENABLELOGIN
              value: "true"
            - name: SECURITY_OAUTH2_ENABLED
              value: "true"
            - name: SECURITY_OAUTH2_AUTOCREATEUSER
              value: "true"
            - name: SECURITY_OAUTH2_ISSUER
              value: "https://auth.mandariini.uk/application/o/pdf/"
            - name: SECURITY_OAUTH2_PROVIDER
              value: "Authentik"
            - name: SECURITY_LOGINMETHOD
              value: "oauth2"
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: "false"
            - name: LANGS
              value:
                en_GB
                de_DE
                fi_FI
          envFrom:
            - secretRef:
                name: envsecrets
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          volumeMounts:
            - name: trainingdata
              mountPath: /usr/share/tessdata
      volumes:
        - name: trainingdata
          persistentVolumeClaim:
            claimName: stirling-pdf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stirling-pdf
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  selector:
    app: stirling-pdf
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.mandariini.uk`)
      kind: Rule
      services:
        - name: stirling-pdf
          port: 8080
  tls:
    secretName: mandariini-uk-tls
