---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searxng
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        storage: longhorn
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:v3.41.1
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: openvpn
            - name: OPENVPN_CUSTOM_CONFIG
              value: /gluetun/custom.conf
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: OPENVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: OPENVPN_PASSWORD
            - name: DNS_KEEP_NAMESERVER
              value: 'on'
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: '10.43.0.10/32'
          volumeMounts:
            - mountPath: /gluetun/custom.conf
              name: searxng-ovpn-conf
              subPath: custom.conf
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:2026.6.20-fd42d4fda
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID
          env:
            - name: SEARXNG_BASE_URL
              value: https://search.mandariini.uk
            - name: SEARXNG_PORT
              value: '8080'
          volumeMounts:
            - name: searxng
              mountPath: /etc/searxng
            - name: searxng-settings-volume
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
      volumes:
        - name: searxng-ovpn-conf
          secret:
            secretName: searxng-ovpn-conf
        - name: searxng
          persistentVolumeClaim:
            claimName: searxng
        - name: searxng-settings-volume
          secret:
            secretName: settings-yml
