---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searxng
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        storage: longhorn
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:v3.41.1
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: SERVER_REGIONS
              valueFrom:
                secretKeyRef:
                  name: envsecrets
                  key: SERVER_REGIONS
            - name: DNS_KEEP_NAMESERVER
              value: 'on'
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: '10.43.0.10/32'
          envFrom:
            - secretRef:
                name: envsecrets
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:2026.4.7-346a46707
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID
          env:
            - name: SEARXNG_BASE_URL
              value: https://search.mandariini.uk
            - name: SEARXNG_PORT
              value: '8080'
          volumeMounts:
            - name: searxng
              mountPath: /etc/searxng
            - name: searxng-settings-volume
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
      volumes:
        - name: searxng
          persistentVolumeClaim:
            claimName: searxng
        - name: searxng-settings-volume
          secret:
            secretName: settings-yml
