---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: searxng
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:2025.3.15-a1d5add71
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: SEARXNG_BASE_URL
              value: https://search.mandariini.uk
            - name: UWSGI_WORKERS
              value: "4"
            - name: UWSGI_THREADS
              value: "4"
          volumeMounts:
            - name: searxng
              mountPath: /etc/searxng
            - name: searxng-settings-volume
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
      volumes:
        - name: searxng
          persistentVolumeClaim:
            claimName: searxng
        - name: searxng-settings-volume
          secret:
            secretName: settings-yml
