---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng
  namespace: searxng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi