apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  project: default
  source:
    chart: wireguard
    repoURL: https://bryopsida.github.io/wireguard-chart
    helm:
      releaseName: wireguard
      valueFiles:
        - values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wireguard