apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wireguard
  namespace: argocd
spec:
  sources:
    - repoURL: https://bryopsida.github.io/wireguard-chart
      chart: wireguard
      targetRevision: 0.28.0
      helm:
        valueFiles:
          - $values/wireguard/values.yml
    - repoURL: https://github.com/villepaukkunen/homelab.git
      targetRevision: HEAD
      ref: values