---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mandariini-uk
  namespace: default
spec:
  secretName: mandariini-uk-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.mandariini.uk"
  dnsNames:
  - "mandariini.uk"
  - "*.mandariini.uk"