container_runtime: containerd

config:
  profiles.yaml: |
    name: default_ip_remediation
    #debug: true
    filters:
     - Alert.Remediation == true && Alert.GetScope() == "Ip"
    decisions:
     - type: ban
       duration: 4h
    #duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
    notifications:
    #   - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
    #   - splunk_default # Set the splunk url and token in /etc/crowdsec/notifications/splunk.yaml before enabling this.
      - http_default   # Set the required http parameters in /etc/crowdsec/notifications/http.yaml before enabling this.
    #   - email_default  # Set the required email parameters in /etc/crowdsec/notifications/email.yaml before enabling this.
    on_success: break
    ---
    name: default_range_remediation
    #debug: true
    filters:
     - Alert.Remediation == true && Alert.GetScope() == "Range"
    decisions:
     - type: ban
       duration: 4h
    #duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
    notifications:
    #   - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
    #   - splunk_default # Set the splunk url and token in /etc/crowdsec/notifications/splunk.yaml before enabling this.
      - http_default   # Set the required http parameters in /etc/crowdsec/notifications/http.yaml before enabling this.
    #   - email_default  # Set the required email parameters in /etc/crowdsec/notifications/email.yaml before enabling this.
    on_success: break
  config.yaml.local: |
    api:
      client:
        unregister_on_exit: true
      server:
        auto_registration: # Activate if not using TLS for authentication
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
            - "127.0.0.1/32"
            - "10.42.0.0/16"
    db_config:
      type: postgresql
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      db_name: crowdsec
      host: crowdsec-pg-rw
      port: 5432
      flush:
        bouncers_autodelete:
          api_key: 1h
        agents_autodelete:
          login_password: 1h
  notifications:
    http.yaml: |
      type: http
      name: http_default
      log_level: info
      format: |
        {{ range . -}}
        {{ $alert := . -}}
        {
          "extras": {
            "client::display": {
            "contentType": "text/markdown"
          }
        },
        "priority": 3,
        {{range .Decisions -}}
        "title": "{{.Type }} {{ .Value }} for {{.Duration}}",
        "message": "{{.Scenario}}  \n\n[crowdsec cti](https://app.crowdsec.net/cti/{{.Value -}})  \n\n[shodan](https://shodan.io/host/{{.Value -}})"
        {{end -}}
        }
        {{ end -}}
      url: http://gotify.gotify.svc.cluster.local/message
      method: POST
      headers:
        X-Gotify-Key: ${GOTIFY_API_KEY}
        Content-Type: application/json

secrets:
  externalSecret:
    name: lapi-secrets

lapi:
  env:
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: envsecrets
          key: ENROLL_KEY
    - name: ENROLL_INSTANCE_NAME
      value: "k3s-cluster"
    - name: ENROLL_TAGS
      value: "k8s"
    - name: BOUNCER_KEY_pfsense
      valueFrom:
        secretKeyRef:
          name: envsecrets
          key: BOUNCER_KEY_pfsense
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: envsecrets
          key: BOUNCER_KEY_traefik
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: crowdsec-postgres-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-postgres-credentials
          key: password
    - name: GOTIFY_API_KEY
      valueFrom:
        secretKeyRef:
          name: envsecrets
          key: GOTIFY_API_KEY
  persistentVolume:
    data:
      enabled: false
    config:
      enabled: false

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
      poll_without_inotify: true
    - namespace: authentik
      podName: authentik-server-*
      program: authentik
      poll_without_inotify: true
    - namespace: nextcloud
      podName: nextcloud-*
      program: nextcloud
      poll_without_inotify: true
    - namespace: nginx-ville
      podName: nginx-ville-*
      program: nginx
      poll_without_inotify: true
    - namespace: jellyfin
      podName: jellyfin-*
      program: jellyfin
      poll_without_inotify: true
  env:
    - name: COLLECTIONS
      value: >-
        crowdsecurity/traefik firix/authentik crowdsecurity/nextcloud crowdsecurity/nginx
        LePresidente/jellyfin

appsec:
  enabled: true
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_configs:
        - crowdsecurity/appsec-default
        - custom/nextcloud
      labels:
        type: appsec
  configs:
    nextcloud.yaml: |
      name: custom/nextcloud
      pre_eval:
       - filter: IsInBand == true && req.URL.Path startsWith "/remote.php/dav/files/"
         apply:
          - RemoveInBandRuleByName("crowdsecurity/vpatch-git-config")
  env:
    - name: COLLECTIONS
      value: crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules